# Generated by Django 2.2.28 on 2023-04-12 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
